-- 2026-09-22 Latpeed 멤버 CSV(오픈특가4 + 얼리버드5) 동기화. Supabase SQL Editor 전체 실행.
-- 규칙: 구독 중 → 다음 결제일 23:59:59 KST 까지 열고 해지마커 해제 / 구독 취소·종료 → 종료일까지 열고 해지마커 세팅.
-- 이미 지난 종료일(과거 이탈자)은 건드리지 않음. 운영자·Dev 계정 제외.
begin;
update users set membership_ends_at='2026-09-22T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-08-22') where lower(email)='ennstudy@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 류효정 구독 중 → 2026-09-22
update users set membership_ends_at='2026-09-24T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-08-24') where lower(email)='sohng10@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 정진송 구독 중 → 2026-09-24
update users set membership_ends_at='2026-09-26T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-08-26') where lower(email)='gloriak1993@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 김하연 구독 중 → 2026-09-26
update users set membership_ends_at='2026-09-29T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-08-29') where lower(email)='yh4571@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 기연아 구독 중 → 2026-09-29
update users set membership_ends_at='2026-09-30T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-08-31') where lower(email)='kjghy3421@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 권은주 구독 중 → 2026-09-30
update users set membership_ends_at='2026-10-02T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-02') where lower(email)='aeisha308@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 채은 구독 중 → 2026-10-02
update users set membership_ends_at='2026-10-03T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-03') where lower(email)='dalsonyu.coda@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 박나영 구독 중 → 2026-10-03
update users set membership_ends_at='2026-10-04T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-04') where lower(email)='jhonly1227@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 김재희 구독 중 → 2026-10-04
update users set membership_ends_at='2026-10-06T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-06') where lower(email)='rinoka@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이명주 구독 중 → 2026-10-06
update users set membership_ends_at='2026-10-07T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-07') where lower(email)='pyoseungyeon720@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 표승연 구독 중 → 2026-10-07
update users set membership_ends_at='2026-10-08T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-08') where lower(email)='isol0613@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 김이솔 구독 중 → 2026-10-08
update users set membership_ends_at='2026-10-08T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-08') where lower(email)='pheobe3308@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 김민희 구독 중 → 2026-10-08
update users set membership_ends_at='2026-10-08T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-08') where lower(email)='attendthetaleof1@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 강부희 구독 중 → 2026-10-08
update users set membership_ends_at='2026-10-08T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-08') where lower(email)='dampoto01@nate.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 김지선 구독 중 → 2026-10-08
update users set membership_ends_at='2026-10-08T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-08') where lower(email)='dhrwjd9172@kakao.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 옥은정 구독 중 → 2026-10-08
update users set membership_ends_at='2026-10-10T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-10') where lower(email)='renouveau_@daum.net' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 김숙 구독 중 → 2026-10-10
update users set membership_ends_at='2026-10-15T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-15') where lower(email)='jeeyeon.jeong@outlook.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 정지연 구독 중 → 2026-10-15
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-20') where lower(email)='dmsghddk@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 황은홍 구독 중 → 2026-10-20
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-20') where lower(email)='unemje@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이정언 구독 중 → 2026-10-20
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-20') where lower(email)='dewyi@kakao.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이슬 구독 중 → 2026-10-20
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-20') where lower(email)='taeshindev@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 신태림 구독 중 → 2026-10-20
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-20') where lower(email)='vhloessook@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 최미숙 구독 중 → 2026-10-20
update users set membership_ends_at='2026-10-21T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-21') where lower(email)='nikkanstudio@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- nikkanstudio@gmail.com 구독 중 → 2026-10-21
update users set membership_ends_at='2026-10-21T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-21') where lower(email)='juhyejoung@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 정주혜 구독 중 → 2026-10-21
update users set membership_ends_at='2026-10-21T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-21') where lower(email)='hyunsungsho@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이수안 구독 중 → 2026-10-21
update users set membership_ends_at='2026-10-21T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-21') where lower(email)='jyjhili5ht@naver.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 정예지 구독 중 → 2026-10-21
update users set membership_ends_at='2026-10-21T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=null, membership_cancel_reason=null, preferences=coalesce(preferences,'{}'::jsonb)||jsonb_build_object('pay_source','latpeed_csv','last_paid_at','2026-09-21') where lower(email)='sykwon024@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 권서윤 구독 중 → 2026-10-21
update users set membership_ends_at='2026-09-22T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='juheepretty135@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 서주희 구독 종료 → 2026-09-22
update users set membership_ends_at='2026-10-06T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='danajun9@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 정다운 구독 취소 → 2026-10-06
update users set membership_ends_at='2026-10-07T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='silviapark292@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 박은실 구독 취소 → 2026-10-07
update users set membership_ends_at='2026-10-11T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='hyun0254@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 임현주 구독 취소 → 2026-10-11
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='soyoon720@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이소윤 구독 취소 → 2026-10-20
update users set membership_ends_at='2026-10-20T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='rbxo4119@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이규태 구독 취소 → 2026-10-20
update users set membership_ends_at='2026-10-21T23:59:59+09:00', cohort='member', unlocked=true, membership_cancel_at=coalesce(membership_cancel_at, now()) where lower(email)='slee937@gmail.com' and coalesce(is_operator,false)=false and coalesce(is_dev_mode,false)=false; -- 이소연 구독 취소 → 2026-10-21
commit;
-- 확인: 위 이메일들의 현재 상태
select email,name,cohort,unlocked,membership_ends_at,membership_cancel_at from users where lower(email) in ('ennstudy@naver.com','sohng10@naver.com','gloriak1993@gmail.com','yh4571@gmail.com','kjghy3421@naver.com','aeisha308@gmail.com','dalsonyu.coda@gmail.com','jhonly1227@gmail.com','rinoka@naver.com','pyoseungyeon720@naver.com','isol0613@naver.com','pheobe3308@gmail.com','attendthetaleof1@gmail.com','dampoto01@nate.com','dhrwjd9172@kakao.com','renouveau_@daum.net','jeeyeon.jeong@outlook.com','dmsghddk@naver.com','unemje@naver.com','dewyi@kakao.com','taeshindev@gmail.com','vhloessook@gmail.com','nikkanstudio@gmail.com','juhyejoung@gmail.com','hyunsungsho@gmail.com','jyjhili5ht@naver.com','sykwon024@gmail.com','juheepretty135@gmail.com','danajun9@gmail.com','silviapark292@gmail.com','hyun0254@gmail.com','soyoon720@gmail.com','rbxo4119@gmail.com','slee937@gmail.com') order by membership_ends_at;
-- 계정 없는 사람(가입 전 결제)은 위 select 에 안 나옴. 그 이메일은 가입하는 순간 trg_users_latpeed_retro 가 아니라 CSV 로 다시 대조 필요.
